# Generated by Django 3.1.7 on 2021-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='PhoneNumber',
            field=models.IntegerField(default=996777777777, verbose_name='Номер телефона'),
        ),
    ]
