# Generated by Django 3.1.7 on 2021-02-23 21:49

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20210224_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150, verbose_name='Имя')),
                ('FamilyName', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('Patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('PhoneNumber', models.IntegerField(default=person.models.random_number, verbose_name='Номер телефона')),
                ('PostCode', models.IntegerField(default=person.models.random_postcode, verbose_name='Индекс почты')),
            ],
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='Country',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
