# Generated by Django 3.1.7 on 2021-02-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20210228_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
