# Generated by Django 3.1.7 on 2021-02-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20210228_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(default='Мужской', max_length=10, verbose_name='Пол'),
        ),
    ]
